---
projectName: Disi-on-platform
image: jembi/platform:latest
logPath: /tmp/logs

packages:
    - disi-on-platform
    - reverse-proxy-nginx
    - elastic-monitoring-metricbeats-filebeats
    - system-monitoring-prometheus-grafana

customPackages:
  - id: disi-on-platform
    path: ../disi-on-platform

profiles:
  - name: local
    packages:
      - disi-on-platform
    envFiles:
      - ./.env.local
    dev: true

  - name: staging
    packages:
      - disi-on-platform
      - reverse-proxy-nginx
      - elastic-monitoring-metricbeats-filebeats
      - system-monitoring-prometheus-grafana
    envFiles:
      - ./.env.stg
    dev: false

  - name: qa
    packages:
      - disi-on-platform
      - reverse-proxy-nginx
      - elastic-monitoring-metricbeats-filebeats
      - system-monitoring-prometheus-grafana
    envFiles:
      - ./.env.qa
    dev: false

  - name: test
    packages:
      - disi-on-platform
    envFiles:
      - ./.env.test
    dev: true
