version: '3.9'

services:
  data-mapper-logstash:
    image: jembi/disi-hiv-poc-logstash:${DISI_LOGSTASH_VERSION:-latest}
    healthcheck:
      test: curl --fail http://localhost:9600 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      ES_ELASTIC: ${ES_ELASTIC:-dev_password_only}
      LS_JAVA_OPTS: ${LS_JAVA_OPTS:--Xmx2g -Xms2g}

  mpi-updater:
    image: jembi/openhim-mediator-mpi-updater:${MPI_UPDATER_VERSION:-latest}
    environment:
      CLIENT_REGISTRY_URL: ${CLIENT_REGISTRY_URL:-http://santedb-mpi:8080}
      FHIR_SERVER_URL: ${FHIR_SERVER_URL:-http://hapi-fhir:8080}
      KAFKA_URL: ${KAFKA_URL:-kafka:9092}
      KAFKA_TOPIC: ${KAFKA_TOPIC:-2xx}
      KAFKA_PATIENT_TOPIC: ${KAFKA_PATIENT_TOPIC:-2xx-patient}
      OPENHIM_MEDIATOR_URL: ${OPENHIM_MEDIATOR_URL:-https://openhim-core:8080}
      TRUST_SELF_SIGNED: ${TRUST_SELF_SIGNED:-true}
      PATIENT_RESOURCES: Encounter,RelatedPerson,Condition,Observation,CarePlan,EpisodeOfCare,Composition,Specimen,ServiceRequest,Immunization,MedicationDispense
      USE_GOLDEN_ID_IN_FHIR_STORE: ${USE_GOLDEN_ID_IN_FHIR_STORE:-false}

  mpi-checker:
    image: jembi/openhim-mediator-mpi-checker:${MPI_CHECKER_VERSION:-latest}
    environment:
      CLIENT_REGISTRY_URL: ${CLIENT_REGISTRY_URL:-http://santedb-mpi:8080}
      FHIR_SERVER_URL: ${FHIR_SERVER_URL:-http://hapi-fhir:8080}
      KAFKA_URL: ${KAFKA_URL:-kafka:9092}
      KAFKA_TOPIC: ${KAFKA_TOPIC:-2xx}
      KAFKA_PATIENT_TOPIC: ${KAFKA_PATIENT_TOPIC:-2xx-patient}
      REGISTER_MEDIATOR: ${REGISTER_MEDIATOR:-true}
      OPENHIM_MEDIATOR_URL: ${OPENHIM_MEDIATOR_URL:-https://openhim-core:8080}
      TRUST_SELF_SIGNED: ${TRUST_SELF_SIGNED:-true}

  reprocess-mediator:
    image: jembi/reprocess-mediator:${REPROCESS_MEDIATOR_VERSION:-disi-latest}
    environment:
      ES_URL: ${ES_URL:-http://instant_analytics-datastore-elastic-search:9200}
      ES_PIT_KEEP_ALIVE: ${ES_PIT_KEEP_ALIVE:-5m}
      KAFKA_CONCURRENCY: ${KAFKA_CONCURRENCY:-2}
      TRUST_SELF_SIGNED: ${TRUST_SELF_SIGNED:-true}
      KAFKA_URL: ${KAFKA_URL:-kafka:9092}
      KAFKA_REPROCESSING_TOPIC: ${KAFKA_REPROCESSING_TOPIC:-reprocess}
      OPENHIM_MEDIATOR_URL: ${OPENHIM_MEDIATOR_URL:-https://openhim-core:8080}
      KAFKA_PARTITION: ${KAFKA_PARTITION:-0}
      OPENHIM_TRANSACTION_URL: ${OPENHIM_TRANSACTION_URL:-http://openhim-core:5001}
      OPENHIM_PASSWORD: ${OPENHIM_ROOT_PASSWORD:-instant101}
      # Temporary Env var until OpenHIM SSL is set up. Can be removed in Prod
      NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED:-0}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
