version: '3.9'

services:
  data-mapper-logstash:
    image: jembi/disi-hiv-poc-logstash
    healthcheck:
      test: curl --fail http://localhost:9600 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      ES_ELASTIC: ${ES_ELASTIC}
      LS_JAVA_OPTS: ${LS_JAVA_OPTS}
      KAFKA_HOSTS: ${KAFKA_HOSTS}

  reprocess-mediator:
    image: jembi/reprocess-mediator:${REPROCESS_MEDIATOR_VERSION}
    environment:
      ES_URL: ${ES_URL}
      ES_PIT_KEEP_ALIVE: ${ES_PIT_KEEP_ALIVE}
      KAFKA_CONCURRENCY: ${KAFKA_CONCURRENCY}
      TRUST_SELF_SIGNED: ${TRUST_SELF_SIGNED}
      KAFKA_URL: ${KAFKA_HOSTS}
      KAFKA_REPROCESSING_TOPIC: ${KAFKA_REPROCESSING_TOPIC}
      OPENHIM_MEDIATOR_URL: ${OPENHIM_MEDIATOR_URL}
      KAFKA_PARTITION: ${KAFKA_PARTITION}
      OPENHIM_TRANSACTION_URL: ${OPENHIM_TRANSACTION_URL}
      OPENHIM_PASSWORD: ${OPENHIM_ROOT_PASSWORD}
      # Temporary Env var until OpenHIM SSL is set up. Can be removed in Prod
      NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
