version: '3.9'

services:
  data-mapper-logstash:
    image: jembi/disi-hiv-poc-logstash:${DISI_LOGSTASH_VERSION}
    healthcheck:
      test: curl --fail http://localhost:9600 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      ES_ELASTIC: ${ES_ELASTIC}
      LS_JAVA_OPTS: ${LS_JAVA_OPTS}
