version: '3.9'

services:
  hapi-fhir-config-importer:
    image: node:erbium-alpine
    environment:
      HAPI_FHIR_BASE_URL: http://hapi-fhir:8080/fhir
      FHIR_IG_URL: ${FHIR_IG_URL}
      NODE_ENV: 'production'
    configs:
      - source: disi-hapi-fhir-fhirConfig.js
        target: /fhirConfig.js
    command: sh -c "cd / && npm i axios@v1.1.3 adm-zip && npm i wait-on -g && wait-on -t 600000 http-get://hapi-fhir:8080 && node /fhirConfig.js"

configs:
  disi-hapi-fhir-fhirConfig.js:
    file: ./fhirConfig.js
    name: disi-hapi-fhir-fhirConfig.js-${disi_hapi_fhir_fhirConfig_js_DIGEST:?err}
    labels:
      name: disi
